In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
patient_notes = pd.read_csv('patient_notes.csv')
features = pd.read_csv('features.csv')

In [3]:
train_data.sample(5)

id  case_num  pn_num  feature_num  \
3757   21591_201         2   21591          201   
113    00224_009         0     224            9   
11018  80525_802         8   80525          802   
457    00804_002         0     804            2   
10037  70730_702         7   70730          702   

                                              annotation  \
3757                                                  []   
113                                   ['heart pounding']   
11018                                   ['Ms', 'female']   
457                                                   []   
10037  ['heavy periods', 'increased length and heavin...   

                                                location  
3757                                                  []  
113                                            ['41 55']  
11018                                   ['0 2', '21 27']  
457                                                   []  
10037  ['23 36', '79 120', '218 240', '218 221;241 289']

In [4]:
train_data = train_data.drop(columns = 'id')

In [5]:
train_data.isnull().sum()

case_num       0
pn_num         0
feature_num    0
annotation     0
location       0
dtype: int64

In [6]:
 train_data['case_num'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [7]:
train_data['pn_num'].unique()

array([   16,    41,    46,    82,   100,   161,   188,   211,   224,
         225,   234,   331,   344,   352,   372,   390,   426,   464,
         489,   495,   510,   575,   583,   585,   625,   653,   669,
         673,   699,   701,   719,   768,   769,   777,   796,   804,
         810,   816,   817,   821,   831,   861,   883,   970,   977,
         987,  1010,  1110,  1115,  1133,  1146,  1149,  1151,  1165,
        1173,  1186,  1200,  1209,  1235,  1250,  1264,  1270,  1281,
        1318,  1376,  1512,  1547,  1581,  1587,  1613,  1622,  1652,
        1692,  1694,  1699,  1723,  1742,  1809,  1835,  1847,  1855,
        1881,  1939,  1948,  2078,  2151,  2163,  2184,  2198,  2201,
        2223,  2271,  2285,  2290,  2308,  2315,  2425,  2428,  2430,
        2436, 10004, 10010, 10013, 10019, 10028, 10030, 10044, 10047,
       10067, 10075, 10101, 10123, 10124, 10131, 10132, 10137, 10174,
       10180, 10181, 10182, 10183, 10192, 10196, 10201, 10206, 10216,
       10223, 10227,

In [8]:
train_data['feature_num'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
       100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 300, 301, 302, 303, 304, 305, 306, 307, 308,
       309, 310, 311, 312, 313, 314, 315, 400, 401, 402, 403, 404, 405,
       406, 407, 408, 409, 500, 501, 502, 503, 504, 505, 506, 507, 508,
       509, 510, 511, 512, 513, 514, 515, 516, 517, 600, 601, 602, 603,
       604, 605, 606, 607, 608, 609, 610, 611, 700, 701, 702, 703, 704,
       705, 706, 707, 708, 800, 801, 802, 803, 804, 805, 806, 807, 808,
       809, 810, 811, 812, 813, 814, 815, 816, 817, 900, 901, 902, 903,
       904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916],
      dtype=int64)

In [9]:
train_data['annotation'].unique()

array(["['dad with recent heart attcak']",
       '[\'mom with "thyroid disease\']', "['chest pressure']", ...,
       "['Did not respond to ibuprofen', 'Did not respond to Tylenol']",
       "['Neck stiffness']", "['photobia']"], dtype=object)

In [10]:
train_data['location'].unique()

array(["['696 724']", "['668 693']", "['203 217']", ..., "['576 594']",
       "['421 437']", "['314 330']"], dtype=object)

In [11]:
train_data.shape

(14300, 5)

In [12]:
location_values = train_data['location'].values

In [13]:
type(location_values)

numpy.ndarray

In [14]:
location_value_list = list(location_values)

In [15]:
location_value_list.count('[]')

4399

In [16]:
annotation_values = train_data['annotation'].values
annotation_value_list = list(annotation_values)

In [17]:
annotation_value_list.count('[]')

4399

In [18]:
train_data.columns

Index(['case_num', 'pn_num', 'feature_num', 'annotation', 'location'], dtype='object')

In [19]:
test_data.columns

Index(['id', 'case_num', 'pn_num', 'feature_num'], dtype='object')

# so we have to predict annotation and location

In [20]:
features.sample(5)

feature_num  case_num                                       feature_text
36           210         2  LMP-2-months-ago-or-Last-menstrual-period-2-mo...
70           501         5                                             Female
45           302         3                             Darker-bowel-movements
84           515         5                Fatigue-OR-Difficulty-concentrating
104          705         7                                            Fatigue

In [21]:
patient_notes.sample(5)

pn_num  case_num                                         pn_history
31273   72684         7  Angela Tompkins is a 35 yo F who presents with...
13549   38678         3  Mr. Hamilton is a 35 yo M presenting with epig...
5641    30615         3  Mr. Hamilton is a 35yo M presenting with 2 mon...
16474   41745         4  Patient is a 45 year old female G2P2 presentin...
30360   71733         7  35 yo female presents after having heavy and l...

In [22]:
features.isnull().sum()

feature_num     0
case_num        0
feature_text    0
dtype: int64

In [23]:
patient_notes.isnull().sum()

pn_num        0
case_num      0
pn_history    0
dtype: int64

## in train and test data feature_num and pn_number are same as in features and patient_notes dataframe

so lets reduce the number of dataframe

In [24]:
new = train_data.merge(features,how='inner')

In [25]:
new.head()

case_num  pn_num  feature_num                        annotation  \
0         0      16            0  ['dad with recent heart attcak']   
1         0      41            0                                []   
2         0      46            0          ['father: heart attack']   
3         0      82            0                     ['Father MI']   
4         0     100            0                        ['Dad-MI']   

      location                                       feature_text  
0  ['696 724']  Family-history-of-MI-OR-Family-history-of-myoc...  
1           []  Family-history-of-MI-OR-Family-history-of-myoc...  
2  ['824 844']  Family-history-of-MI-OR-Family-history-of-myoc...  
3  ['622 631']  Family-history-of-MI-OR-Family-history-of-myoc...  
4  ['735 741']  Family-history-of-MI-OR-Family-history-of-myoc...

In [26]:
new = new.merge(patient_notes,how='inner')

In [27]:
new.head()

case_num  pn_num  feature_num                                annotation  \
0         0      16            0          ['dad with recent heart attcak']   
1         0      16            1             ['mom with "thyroid disease']   
2         0      16            2                        ['chest pressure']   
3         0      16            3      ['intermittent episodes', 'episode']   
4         0      16            4  ['felt as if he were going to pass out']   

               location                                       feature_text  \
0           ['696 724']  Family-history-of-MI-OR-Family-history-of-myoc...   
1           ['668 693']                 Family-history-of-thyroid-disorder   
2           ['203 217']                                     Chest-pressure   
3  ['70 91', '176 183']                              Intermittent-symptoms   
4           ['222 258']                                        Lightheaded   

                                          pn_history  
0  HPI: 17yo M presents with palpitations. Patien...  
1  HPI: 17yo M presents with palpitations. Patien...  
2  HPI: 17yo M presents with palpitations. Patien...  
3  HPI: 17yo M presents with palpitations. Patien...  
4  HPI: 17yo M presents with palpitations. Patien...

In [28]:
new_test = test_data.merge(features,how='inner')

In [29]:
new_test = new_test.merge(patient_notes,how = 'inner')

In [30]:
new_test.shape,new.shape

((5, 6), (14300, 7))

In [31]:
new_test.columns

Index(['id', 'case_num', 'pn_num', 'feature_num', 'feature_text',
       'pn_history'],
      dtype='object')

In [32]:
new.columns

Index(['case_num', 'pn_num', 'feature_num', 'annotation', 'location',
       'feature_text', 'pn_history'],
      dtype='object')

In [33]:
new_test = new_test.drop(columns = 'id')

In [34]:
new_test.columns

Index(['case_num', 'pn_num', 'feature_num', 'feature_text', 'pn_history'], dtype='object')

In [35]:
new = new[new['annotation'] != '[]']

In [36]:
new = new[new['location'] != '[]']

In [37]:
new = new[new['pn_history'] != '[]']

In [38]:
new = new[new['feature_text'] != '[]']

In [39]:
new_test = new_test[new_test['feature_text'] != '[]']

In [40]:
new_test = new_test[new_test['pn_history'] != '[]']

In [41]:
new.shape , new_test.shape

((9901, 7), (5, 5))

In [42]:
pip install -U spacy

Note: you may need to restart the kernel to use updated packages.


In [43]:
import spacy

In [44]:
nlp = spacy.load('en_core_web_sm')

In [45]:
l = [i for i in new['annotation']]
l = str(l)

In [46]:
annotation_object = nlp(l)

In [47]:
annotation_object

["['dad with recent heart attcak']", '[\'mom with "thyroid disease\']', "['chest pressure']", "['intermittent episodes', 'episode']", "['felt as if he were going to pass out']", "['adderall', 'adderrall', 'adderrall']", "['palpitations', 'heart beating/pounding']", "['3-4 months of']", "['17yo']", "['M']", "['MOM HAS THYROID PROBLEMS']", "['PRESSURE ON HER CHEST']", "['COMES AND GOES', 'HAPPENED 5-6 TIMES']", "['SOB']", "['HEART POUNDING']", "['STARTED 2-3 MO AGO']", "['17 Y/O']", "['M']", "['father: heart attack']", "['mom: thyroid issues']", "['sporadically']", "['light headedness']", "['has not had any cold/heat intolerance']", "['adderall', 'Adderall']", "['SOB']", "['palpitations', 'palpitations', 'palpitations']", "['for 2-3 months']", "['17yo']", "['M']", "['Father MI']", "['Mom thyroid problem']", "['episodic', '5-6 times']", "['light headedness']", "['aderall']", "['shortness of breath']", "['heart pounding', 'heart racing', 'heart pounding']", "['3 months of', 'over the past 

In [48]:
m = [i for i in new['feature_text']]
n = [i for i in new['pn_history']]

In [49]:
nlp.max_length = 100000000

In [ ]:
feature_text_object = nlp(str(m))
pn_history_object = nlp(str(n))

In [ ]:
feature_text_object

In [ ]:
pn_history_object

In [ ]:
from spacy.matcher import Matcher